// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package accounts

import (
	"context"
	"github.com/google/uuid"
	"github.com/indigowar/delivery/internal/entities"
	"sync"
)

// Ensure, that StorageMock does implement Storage.
// If this is not the case, regenerate this file with moq.
var _ Storage = &StorageMock{}

// StorageMock is a mock implementation of Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked Storage
//		mockedStorage := &StorageMock{
//			AddFunc: func(ctx context.Context, account *entities.Account) (*entities.Account, error) {
//				panic("mock out the Add method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.Account, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByPhoneFunc: func(ctx context.Context, phone string) (*entities.Account, error) {
//				panic("mock out the GetByPhone method")
//			},
//			UpdateFunc: func(ctx context.Context, account *entities.Account) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedStorage in code that requires Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, account *entities.Account) (*entities.Account, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.Account, error)

	// GetByPhoneFunc mocks the GetByPhone method.
	GetByPhoneFunc func(ctx context.Context, phone string) (*entities.Account, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, account *entities.Account) error

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account *entities.Account
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByPhone holds details about calls to the GetByPhone method.
		GetByPhone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Phone is the phone argument value.
			Phone string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account *entities.Account
		}
	}
	lockAdd        sync.RWMutex
	lockDelete     sync.RWMutex
	lockGetByID    sync.RWMutex
	lockGetByPhone sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Add calls AddFunc.
func (mock *StorageMock) Add(ctx context.Context, account *entities.Account) (*entities.Account, error) {
	if mock.AddFunc == nil {
		panic("StorageMock.AddFunc: method is nil but Storage.Add was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account *entities.Account
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, account)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedStorage.AddCalls())
func (mock *StorageMock) AddCalls() []struct {
	Ctx     context.Context
	Account *entities.Account
} {
	var calls []struct {
		Ctx     context.Context
		Account *entities.Account
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *StorageMock) Delete(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("StorageMock.DeleteFunc: method is nil but Storage.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedStorage.DeleteCalls())
func (mock *StorageMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *StorageMock) GetByID(ctx context.Context, id uuid.UUID) (*entities.Account, error) {
	if mock.GetByIDFunc == nil {
		panic("StorageMock.GetByIDFunc: method is nil but Storage.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedStorage.GetByIDCalls())
func (mock *StorageMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByPhone calls GetByPhoneFunc.
func (mock *StorageMock) GetByPhone(ctx context.Context, phone string) (*entities.Account, error) {
	if mock.GetByPhoneFunc == nil {
		panic("StorageMock.GetByPhoneFunc: method is nil but Storage.GetByPhone was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Phone string
	}{
		Ctx:   ctx,
		Phone: phone,
	}
	mock.lockGetByPhone.Lock()
	mock.calls.GetByPhone = append(mock.calls.GetByPhone, callInfo)
	mock.lockGetByPhone.Unlock()
	return mock.GetByPhoneFunc(ctx, phone)
}

// GetByPhoneCalls gets all the calls that were made to GetByPhone.
// Check the length with:
//
//	len(mockedStorage.GetByPhoneCalls())
func (mock *StorageMock) GetByPhoneCalls() []struct {
	Ctx   context.Context
	Phone string
} {
	var calls []struct {
		Ctx   context.Context
		Phone string
	}
	mock.lockGetByPhone.RLock()
	calls = mock.calls.GetByPhone
	mock.lockGetByPhone.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *StorageMock) Update(ctx context.Context, account *entities.Account) error {
	if mock.UpdateFunc == nil {
		panic("StorageMock.UpdateFunc: method is nil but Storage.Update was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Account *entities.Account
	}{
		Ctx:     ctx,
		Account: account,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, account)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedStorage.UpdateCalls())
func (mock *StorageMock) UpdateCalls() []struct {
	Ctx     context.Context
	Account *entities.Account
} {
	var calls []struct {
		Ctx     context.Context
		Account *entities.Account
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
