name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.21.6
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test
